transferwise/pipelinewise-target-snowflake

target_snowflake/__init__.py, target_snowflake/db_sync.py, tests/integration/test_target_snowflake.py, tests/unit/test_unit.py
Information_schema_columns cache is a copy of snowflake INFORMATION_SCHEMA.COLUMNS table to avoid the error of `Information schema query returned too much data. Please repeat query with more selective predicates.`
Snowflake gives the above error message when running multiple taps in parallel (approx. >10 taps) and when these taps selecting from information_schema at the same time. To avoid this problem we maintain a local copy of the INFORMATION_SCHAME.COLUMNS table and it's keep updating automatically whenever it's needed.
=> Caching information_schema.columns

setup.py, target_snowflake/__init__.py, target_snowflake/db_sync.py, tests/integration/test_target_snowflake.py
Query and load the cache table into memory at startup and pass it to every component at runtime. This minimises the number of queries to the cache table in Snowflake.
Currently we run this query every time when a singer `SCHEMA` message consumes:
```
SELECT LOWER(c.table_schema) table_schema, LOWER(c.table_name) table_name, c.column_name, c.data_type
FROM pipelinewise.columns c
WHERE 1 = 1 AND LOWER(c.table_schema) = '{target_schema}`
```
For example if a tap has 200 tables then we run the above query 200 times. Each of them takes a couple of seconds and it gives 4-5 extra minute to the startup time.
=> Optimised caching

requirements.txt
The old snowflake python connector now fails with an error asn1cryptokeys.PublicKeyInfo().unwrap() has been removed, please use oscrypto.asymmetric.PublicKey().unwrap() instead. Snowflake have fixed this but it requires the latest snowflake-connector-python (2.0.1)
See: https://github.com/snowflakedb/snowflake-connector-python/commit/5ad17f6491c1bfe87facd8b367fd51b519f2fd03
=> Bump to latest snowflake-connector-python version is required. Current version fails to connect to snowflake.

target_snowflake/__init__.py
Fixes #41
STATE message is not mandatory by the singer spec and target-snowflake should not expect that the tap already sent a valid STATE message when flushing batches. Further details in #41
=> Update flushed_state only if state received from tap

README.md, target_snowflake/__init__.py, tests/integration/resources/messages-with-invalid-records.json, tests/integration/test_target_snowflake.py, tests/integration/utils.py
Adds `validate_records` option:
(Default: False) Validate every single record message to the corresponding JSON schema. This option is disabled by default and invalid RECORD messages will fail only at load time by Snowflake. Enabling this option will detect invalid records earlier but could cause performance degradation.
=> Add optional validate_records option

README.md, setup.py, target_snowflake/__init__.py, tests/integration/test_target_snowflake.py
Currently every temporary CSV file created in the system `/tmp` directory. This PR makes it customisable by a new `tmp_dir` optional config parameter.
This PR is related to https://github.com/transferwise/pipelinewise/pull/304 where PipelineWise passes the generated `temp_dir` path to target connectors automatically.
=> [AP-415] Add temp_dir optional parameter to config

.circleci/config.yml, sample_logging.conf, setup.py, target_snowflake/__init__.py, target_snowflake/db_sync.py, tests/integration/test_target_snowflake.py, tests/unit/test_target_snowflake.py
Switching to using Transferwise's singer fork instead of the Stitch's, this allows to configure logging however we want.
Given that pipelinewise-target-snowflake is also a pip module, it doesn't force any logging configuration and it's up to the final caller to do so.
Example of logs when `LOGGIN_CONG_FILE` is set:
```
time=2020-02-06 15:02:06 name=target_snowflake level=INFO message=Table 'sam_test.test_binary' exists
time=2020-02-06 15:02:17 name=target_snowflake level=INFO message=Uploading 3 rows to external snowflake stage on S3
time=2020-02-06 15:02:17 name=target_snowflake level=INFO message=Target S3 bucket: tw-staging-analyticsdb-etl, local file: /tmp/records_nrof1wdy.csv, S3 key: snowflake-imports-test/pipelinewise_tap_mysql_test-test_binary_20200206-150217-810000.csv …
```
=> [AP-473] refactor Logging

target_snowflake/__init__.py, target_snowflake/db_sync.py, tests/integration/resources/messages-with-reserved-name-as-table-name.json, tests/integration/test_target_snowflake.py
Sometimes the stream/table name is a reserved word in Snowflake and the current implementation doesn't support that so we end up getting a sql error.
Wrap the table name in double quotes and capitalize it to make it safe to be in a Snowflake sql query. 
The streams with one schema where the table is `order`:
```
{"type": "STATE", "value": {"currently_syncing": "my_db-order"}}
{"type": "SCHEMA", "stream": "my_db-order", "schema": {"properties": {"data": {"inclusion": "available", "format": "binary", "type": ["null", "string"]}, "id": {"inclusion": "automatic", "format": "binary", "type": ["null", "string"]}, "created_at": {"inclusion": "available", "format": "date-time", "type": ["null", "string"]}}, "type": "object"}, "key_properties": ["id"]}
{"type": "ACTIVATE_VERSION", "stream": …
```
=> [AP-549] support reserved words as table names

target_snowflake/__init__.py, target_snowflake/db_sync.py, tests/integration/test_target_snowflake.py
**Summary**
This PR refactoring the code to use `SHOW SCHEMAS|TABLES|COLUMNS` queries instead of `INFORMATION_SCHEMA`. Information schema queries are slow in general and can cause failing parallel running taps with `snowflake.connector.errors.ProgrammingError: 090030 (22000): Information schema query returned too much data.  Please repeat query with more selective predicates.`
This PR is also getting rid of `PIPELINEWISE.COLUMNS` table because the `SHOW` queries basically provide the same information with good performance.
**Solution**
After some research it turns out this is a generic problem in snowflake `INFORMATION_SCHEMA` and other projects have similar issues as well. For example DBT:
* https://github.com/fishtown-analytics/dbt/issues/1877
* …
=> [AP-591] Use SHOW SCHEMAS|TABLES|COLUMNS instead of INFORMATION_SCHEMA

target_snowflake/__init__.py
The upstream pipelinewise-singer-python is going to bump jsonschema-2.6.0 the the more recent 3.2.0. As part of the upgrade we also want to replace the old Draft4Validator to Draft7Validator.
Related PR at https://github.com/transferwise/pipelinewise-singer-python/pull/10
=> Switch to Draft7Validator

target_snowflake/db_sync.py, tests/integration/test_target_snowflake.py
This is a fix for https://github.com/transferwise/pipelinewise-target-snowflake/issues/78
When multiple queries running in one transaction, the [db_sync.query](https://github.com/transferwise/pipelinewise-target-snowflake/blob/afb9c92d2f1f0c539b37f5ebeb1c7370df27d05d/target_snowflake/db_sync.py#L308) function should return the result of the last query in the transaction. This is not the case when the query in the transaction returns zero record. When this happens, the function returns something wrong:
```
[{'status': 'Statement executed successfully.'}]
```
The output above is the output of the `START TRANSACTION` statement which is wrong. In this case the [db_sync.query](https://github.com/transferwise/pipelinewise-target-snowflake/blob/afb9c92d2f1f0c539b37f5ebeb1c7370df27d05d/target_snow …
=> [AP-760] Fixed bad return value from multiple queries in one transaction

target_snowflake/db_sync.py
Changing log level from `INFO` to `ERROR` when no primary key found.
This is useful if PPW configured to use alert handlers. The error will be extracted from the log and send in the alerts.
ATM when primary not found target-snowflake logs it as:
```
time=2020-07-22 14:32:49 logger_name=target_snowflake log_level=INFO message=Cannot find ['id'] primary key(s) in record: {"x": "abcd", "y": "abcd"}'
```
The `INFO` should be `ERROR` instead.
=> Change log level when no primary key

.gitignore, README.md, setup.py, target_snowflake/db_sync.py, tests/integration/.env.sample, tests/integration/utils.py
- Add `s3_acl: acl-name` to SF target config, so an object's ACL can be altered after uploading
- Add `.env` support for integration tests
=> Support ACL for S3 uploads

README.md, target_snowflake/db_sync.py, tests/integration/test_target_snowflake.py
This target is currently using hard coded `aws_access_key_id` and `aws_secret_access_key` to connect to S3 external stages. Instead of hard coded credentials we should be able to use env vars, AWS profile based authentication and IAM roles as alternative authentication methods when connecting to exteranal stage on S3.
This PR adds these features to this target.
* config.json: `aws_profile` -  Env var: `AWS_PROFILE`
* config.json: `aws_access_key_id` - Env var: `AWS_ACCESS_KEY_ID`
* config.json: `aws_secret_access_key` - Env var: `AWS_SECRET_ACCESS_KEY`
* config.json: `aws_session_token` - Env var: `AWS_SESSION_TOKEN`
* config.json: `s3_endpoint_url` - Allowing to use non-native s3 account
* config.json: `s3_region_name` - Region name when creating new connection
The target is using …
=> [AP-822] S3 profile based auth, session_token, AWS stage creds from env vars

target_snowflake/db_sync.py, tests/integration/test_target_snowflake.py
This PR set  [QUOTED_IDENTIFIERS_IGNORE_CASE](https://docs.snowflake.com/en/sql-reference/parameters.html#quoted-identifiers-ignore-case) session parameter to `FALSE` when connecting to snowflake. This parameter can set for account, user and session and when it's not the default `FALSE` then target-snowflake fails.
**Problem**:  [QUOTED_IDENTIFIERS_IGNORE_CASE](https://docs.snowflake.com/en/sql-reference/parameters.html#quoted-identifiers-ignore-case) is a snowflake parameter that specifies whether the case of letters is ignored for all object identifiers in double quotes. Quoted identifiers expected as case sensitive values in multiple places, for example when creating columns with reserved words, versioning columns, getting column informations, etc. 
**To reproduce**:
1. `ALTER …
=> [AP-824] Set QUOTED_IDENTIFIERS_IGNORE_CASE session parameter to false

requirements.txt, setup.py
On python 3.8 it was causing this errror : 
`Traceback (most recent call last):
File ".venv/pipelinewise-target-snowflake/bin/target-snowflake", line 11, in <module>
load_entry_point('pipelinewise-target-snowflake', 'console_scripts', 'target-snowflake')()
File ".venv/pipelinewise-target-snowflake/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File ".venv/pipelinewise-target-snowflake/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
return ep.load()
File ".venv/pipelinewise-target-snowflake/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2462, in load
return self.resolve()
File ".venv/pipelinewise-target-snowflake/lib/python3.8/site-packages/ …
=> Bump Joblib to lastest version. Was failing on python 3.8

README.md, target_snowflake/db_sync.py, tests/integration/test_target_snowflake.py, tests/unit/test_db_sync.py
Sometimes it's needed to analyse queries in Snowflake that was created by this target connector. `QUERY_HISTORY` snowflake views keep all the queries but hard to link them back to the target, especially when the same target used by multiple taps.
Introducing `query_tag` optional config property to tag executed queries in Snowflake. Replaces tokens `schema` and `table` with the appropriate values. The tags are displayed in the output of the Snowflake `QUERY_HISTORY`, `QUERY_HISTORY_BY_*` functions.
The main PipelineWise will generate the `query_tag` automatically for every snowflake targets including the `tap_id`, and this target will add the target `schema` and target `table` dynamically. 
=> [AP-866] Add query_tag config property

README.md, target_snowflake/db_sync.py, tests/integration/test_target_snowflake.py
Addressing #96.
Target snowflake can use only the user's default role to load data.
This PR adds the optional `role` parameter to `config.json`. This allows to use custom roles when loading data and not only the user's default role.
=> [GITHUB-96] Add optional role parameter

README.md, target_snowflake/db_sync.py, tests/integration/test_target_snowflake.py, tests/unit/test_db_sync.py
This PR adds `{database}` token to `query_tag` template. The value evaluated at runtime and replaced to the actual database name.
The PR adds a few more test cases as well and fixes an edge case with JSON formatted `query_tags` with quotes.
Replace template variables with JSON compatible, quote escaped values.
=> [AP-866] Add database token to query_tag

target_snowflake/db_sync.py, tests/integration/test_target_snowflake.py
There seems to be an intermittent issue when running a list of query using `DBSync.query` method, the order in Snowflake history shows that Start transaction is the second instead of first, this messes up with queries that rely on `LAST_QUERY_ID()` results. for example the `select .. from TABLE(RESULT_SCAN(LAST_QUERY_ID()))` fails with:
```
SQL compilation error: error line 1 at position 7 invalid identifier '"schema_name"'
```
* Force start transaction first but running it outside of the loop.
* To reduce the dynamic nature of `select .. from TABLE(RESULT_SCAN(LAST_QUERY_ID()));`,  make use of the SF connector cursor ability to return the query id with the attribute `sfqid` and then pass it to the next query in the list as a named parameter.
* A reserved prepared statement param …
=> Replace usage of LAST_QUERY_ID with query id from cursor

target_snowflake/__init__.py, tests/integration/resources/messages-with-unexpected-types.json, tests/integration/test_target_snowflake.py, tests/unit/test_target_snowflake.py
In some case, target-snowflake receives a record where property has `date-time` or `time` format  but the value is an integer or not string.
This is not a bug in target, but rather the source. More info could be seen if `validate_records` is set to true, as it would raise an exception, otherwise, no validation would happen and something will fail later without further logs.
```
File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/target_snowflake/init.py", line 136, in reset_new_value
parser.parse(record[key])
File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1374, in parse
return DEFAULTPARSER.parse(timestr, **kwargs)
File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/dateutil/parser/_parser.py", line …
```
=> Parsing dates: Add checks and logs

target_snowflake/__init__.py, target_snowflake/db_sync.py, target_snowflake/file_format.py, tests/integration/test_target_snowflake.py
target-snowflake added parquet support. To detect the required file format it's running an SQL command: `SHOW FILE FORMATS`.
At the moment this SQL triggered to run for every selected table but it's enough to run only once. These extra queries add unnecessary overhead on some taps that's required to load lot of tables. For example a tap where more than hundred tables selected, the tap is waiting for 5 minutes to retrieve all the hundred of SQL queries before it starts reading the binlog.
The `SHOW FILE FORMATS` command should run only once at the beginning similar to the `SHOW COLUMNS IN SCHEMA` [here](https://github.com/transferwise/pipelinewise-target-snowflake/blob/8b5f756270fd8356bba66afcb49a51d007ff4c71/target_snowflake/db_sync.py#L586)
What types of changes does your code introduce …
=> [AP-983] Run SHOW FILE FORMATS SQL only once

README.md, target_snowflake/__init__.py, target_snowflake/db_sync.py, target_snowflake/upload_clients/base_upload_client.py, target_snowflake/upload_clients/s3_upload_client.py, target_snowflake/upload_clients/snowflake_upload_client.py, tests/integration/test_target_snowflake.py, tests/unit/test_db_sync.py, tests/unit/test_target_snowflake.py
The archive_load_files feature added in https://github.com/transferwise/pipelinewise-target-snowflake/pull/178 only allows archival in the same S3 bucket as is used to the Snowflake imports.
This means that S3 bucket versioning will either be enabled for both archived files and the temporary load files, or neither.
Versioning makes sense for archived files, where accidental deletes could be problematic. It does not, however, make sense for the temporary load files, and having it enabled for them will incur unnecessary cost.
This PR allows configuring a separate S3 bucket to be used as the archive destination, as well as customizing the S3 prefix used.
=> AP1011 - Custom archive bucket/folder

target_snowflake/db_sync.py, target_snowflake/exceptions.py, tests/unit/test_db_sync.py
Some exceptions logging original record messages. We should hide them.
Don't dump the original record messages as logs.
=> Do not log record message

target_snowflake/db_sync.py
This increases the max_records allowed by a Snowflake target when the running the schema columns check `SHOW COLUMNS IN SCHEMA snowflake_db.destination_schema`
This issue is caused by the fact that my source database has many monthly partition tables of same table so we have many versions of the same table, which duplicates the number of columns, albeit for different partitions.
See https://github.com/transferwise/pipelinewise-target-snowflake/issues/210.
Increases the maximum number of columns allowed by pipelinewise snowflake target such that we can handle larger databases sizes.
Note, there is no test coverage for this field. Is that something you want me to add? I suppose I could test the methods for various inputs or something like that.
=> AP-210 increase max_records by an order of magnitude

target_snowflake/__init__.py
Due to a high number of schema messages due to handling TOAST messages in https://github.com/transferwise/pipelinewise-tap-postgres/issues/146 all the records are constantly flushed resulting in very slow performance.
This changes ensures the `flush_all_streams` configuration setting is honored when a new schema message arrives in the target. If this is not set, then only the records for the current stream are flushed instead for all rows.
=> Consider flush_all_streams for schema updates

target_snowflake/db_sync.py, target_snowflake/flattening.py, tests/unit/test_db_sync.py
When a MERGE or COPY query fails, it's not easy to find out the table it failed for.
Improve logging for failed MERGE and COPY queries.
=> [AP-1122] improve logging for failed MERGE and COPY queries

Makefile, target_snowflake/db_sync.py, tests/integration/resources/messages-with-changing-pk.json, tests/integration/resources/messages-with-null-pk.json, tests/integration/test_target_snowflake.py, tests/unit/test_db_sync.py
1. When the source/tap changes the key-properties of a stream, this doesn't reflect in the snowflake table, PKs remain the same and don't change accordingly.
2. SF enforces non-nullability on columns marked as PK. We don't want such behavior.
3. target accepts records that have null values in the fields in key-properties, ie accepts records where PKs are null, then it treats all these records as the same record and updates it in memory to only keep the latest one, this can cause data quality issue.
1. Monitor changes to `key-properties` in SCHEMA messages:
* if it becomes empty, then drop any existing PK from the table
* if there are new columns or columns are no longer key properties, refresh the table PK constraint to reflect the new PK.
2. Drop `non null` constraint on columns that are …
=> AP-1110 Handle change to key properties and remove non-nullability constraint

.github/workflows/ci.yaml, setup.py
Python 3.6 has reached EOL.
Dropping 3.6 from CI matrix and adding 3.9
=> Drop Support for Python 3.6 and add 3.9

CHANGELOG.md, setup.py
Prep to release the following changes:
*Fixes*
- Respecting `flush_all_streams` when SCHEMA messages arrive.
- Improve logging for failed merge & copy queries.
- Drop NOT NULL constraint from primary key columns.
- Update PK constraints according to changes to SCHEMA's key properties.
*Changes*
- Dropping Python 3.6 from CI matrix
- Adding Python 3.9 to CI matrix
- Bump pytest to `7.1.1`
- Bump boto3 to `1.21`
=> Release v2.0.0

target_snowflake/db_sync.py, tests/integration/resources/messages-with-falsy-pk-values.json, tests/integration/resources/messages-with-new-pk.json, tests/integration/test_target_snowflake.py, tests/unit/test_db_sync.py
1. target runs `alter table .. drop primary key` even when table has no such constraint
2. target raises `PrimaryKeyNotFoundException` when it encounteres a record where pk value is falsy
1. only drop pk constraint if it exists
2.  only raise `PrimaryKeyNotFoundException` if  pk field in record is either non-existent or is explicitly null.
=> AP-1205 AP-1206 Fix issues with primary keys
