target_snowflake/db_sync.py

Not the final solution, but will buy some time

Some improvement

---

setup.py
target_snowflake/db_sync.py
tests/integration/test_target_snowflake.py

* bump snowflake-connector-python to latest
* Use secure connection
* Fix tests to run in multi-envs in parallel

Bump snowflake python to latest

---

setup.py
target_snowflake/__init__.py
tests/unit/test_target_snowflake.py

https://transferwise.atlassian.net/browse/AP-369

1.1.7: review all dates/times in records and adjust them

---

setup.py
target_snowflake/__init__.py
target_snowflake/db_sync.py

remove unnecessary creation of tmp files

---

CHANGELOG.md
setup.py

Should be merged after https://github.com/transferwise/pipelinewise-target-snowflake/pull/62

Update changelog and bump version

---

CHANGELOG.md
setup.py

v1.6.2 and changelog

---

README.md

Document all the required roles and permissions for target-snowflake.

[DOC] Update required privileges in README

---

README.md

[DOC] Fix grants

---

CHANGELOG.md
setup.py

v1.6.6 and changelog

---

.gitignore
README.md
target_snowflake/__init__.py
target_snowflake/db_sync.py
target_snowflake/s3_upload_client.py
target_snowflake/snowflake_upload_client.py
tests/integration/test_target_snowflake.py

This is my take on #22 
I've moved the S3 logic to S3UploadClient and implemented  a snowflake upload client . 
It would then be easy to implement Azure storage or GCP . 
https://transferwise.atlassian.net/wiki/spaces/EKB/pages/1401189673/Change+Classifications+and+Expectations) Label (`change:standard`, `change:impactful`, `change:emergency`)

Use internal table stage

---

README.md
target_snowflake/db_sync.py
tests/integration/test_target_snowflake.py
tests/unit/test_db_sync.py

Option to use [snowflake table stages](https://docs.snowflake.com/en/user-guide/data-load-local-file-system-create-stage.html#table-stages) to load data is not documented and tested completely.
Document and add tests for table and external stage configurations.

Document and test internal table stage option

---

target_snowflake/db_sync.py
target_snowflake/s3_upload_client.py
target_snowflake/snowflake_upload_client.py

Some lines are not nicely formatted.
Minor reformatting of few lines in files.

Fix a few formatting issues

---

CHANGELOG.md
setup.py

Release 1.10.1

---

.circleci/config.yml
.github/workflows/ci.yaml
Makefile
setup.py
tests/integration/test_target_snowflake.py
tests/unit/test_db_sync.py
tests/unit/test_file_format.py

* CircleCi byebye
* Move some CI steps to GHA
* Create Makefile for reproducible commands
* tidy up dependencies and imports

AP-1039 Migrate some CI to GHA

---

CHANGELOG.md
setup.py

Release 1.14.0

---

CHANGELOG.md
setup.py

Release 1.14.1

---

README.md

There is a typo in the README.
Fix the typo in the README.

Typo: 'snowflake' not 'snowfale'

---

setup.py
target_snowflake/upload_clients/s3_upload_client.py

we have a bunch of PRs from dependabot, it will be slow to to run CI of each one and some have breaking changes.
* Update dependencies
* fix some breaking changes
* remove redundant dependencies.

Bump dependencies in bulk

---

CHANGELOG.md
setup.py

Release 1.15.0

---

CHANGELOG.md
setup.py

Release 2.0.1

---

setup.py
target_snowflake/__init__.py
target_snowflake/db_sync.py
target_snowflake/file_formats/csv.py
target_snowflake/flattening.py
tests/integration/test_target_snowflake.py
tests/unit/test_db_sync.py
tests/unit/test_flattening.py
tests/unit/test_target_snowflake.py

Reverts transferwise/pipelinewise-target-snowflake#204

Revert "[AP-1052] Switch to ujson"

---

target_snowflake/db_sync.py

Resolve issue #289 
Update max_records by an order of magnitude

Update max_records by order of magnitude
